version: "3.9"
services:
  database:
    image: "mysql:8.0-debian"
    restart: "unless-stopped"
    environment:
      MYSQL_HOST: ${DATABASE_HOST}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - "./docker/mysql:/var/lib/mysql"
  pma:
    image: "phpmyadmin:5.2"
    restart: "unless-stopped"
    environment:
      PMA_HOST: "database"
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - "database"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"
      - "traefik.http.routers.goshort-pma.entrypoints=websecure"
      - "traefik.http.routers.goshort-pma.rule=Host(`${TRAEFIK_PMA_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.goshort-pma.tls=true"
  backend:
    build:
      context: "./apps/backend/"
      dockerfile: "Dockerfile"
      target: ${ENVIRONMENT}
    env_file:
      - "./.env"
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      - "database"
    volumes:
      - "./apps/backend:/usr/src/app"
      - "shared:/srv/www/public"
      # - "shared:/usr/src/app/public"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"
      - "traefik.http.routers.goshort-backend.entrypoints=websecure"
      - "traefik.http.routers.goshort-backend.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.goshort-backend.tls=true"
  frontend:
    build:
      context: "./apps/frontend/"
      dockerfile: "Dockerfile"
      target: ${ENVIRONMENT}
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - "./apps/frontend:/usr/src/app"
      - "shared:/usr/src/app/dist"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"
      - "traefik.http.routers.goshort-frontend.entrypoints=websecure"
      - "traefik.http.routers.goshort-frontend.rule=Host(`${TRAEFIK_FRONTEND_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.goshort-frontend.tls=true"
volumes:
  shared:
    driver: "local"
networks:
  default:
    name: ${TRAEFIK_NETWORK}
    external: true
    